In [18]:
import pandas as pd

# Importación

In [19]:
df = pd.read_csv('../data/ElArticoDiscos-inventory-raw.csv')

df.columns=[e.lower().replace(' ', '_') for e in df.columns]

In [20]:
df.head()

,listing_id,artist,title,label,catno,format,release_id,status,price,listed,comments,media_condition,sleeve_condition,accept_offer,external_id,weight,format_quantity,location
0,1161793621,King Tutt,Comin' Out / Even Though,T.K. Disco,458,"12""",694699,Sold,"6,0",2021-03-17 06:25:42,Original T.K. Disco Sleeve,Near Mint (NM or M-),Generic,Y,NaN,230,1,039
1,1364731297,King Crimson,In The Court Of The Crimson King,"Polydor, EG",800 030-2,"CD, Album, RE",2981367,Sold,"17,0",2021-03-17 07:05:50,NaN,Near Mint (NM or M-),Near Mint (NM or M-),Y,NaN,85,1,HBalda12
2,1287142647,David S. Ware String Ensemble,Threads,Thirsty Ear,THI57137.2,"CD, Album",1099653,Sold,"11,0",2021-03-17 07:08:13,SEALED (Precintado),Mint (M),Mint (M),Y,NaN,85,1,HCajón01
3,1287144780,David Eyges,The Captain,MidLantic Records,MR2002-103,"CD, Album, RE",10108236,Sold,"9,99",2021-03-17 07:08:14,Almost like new. Private Collection. Close to ...,Near Mint (NM or M-),Near Mint (NM or M-),Y,NaN,85,1,HCajón01
4,1362016279,"Dmitri Shostakovich, Государственный Симфониче...","Symphony No 5 In D Minor Op 47, Symphony No 9 ...",Olympia (2),OCD 113,CD,10422040,Sold,"9,99",2021-03-17 07:08:14,NaN,Near Mint (NM or M-),Near Mint (NM or M-),Y,NaN,85,1,HBalda20

# Transformación

In [21]:
df.drop(['catno', 'listed', 'comments', 'external_id', 'location'], axis = 1, inplace=True)

In [22]:
df.price = df.price.apply(lambda x: str(x).replace('.',','))
df.artist = df.artist.apply(lambda x: x.split('(')[0])
df.label = df.label.apply(lambda x: x.split('(')[0])

In [23]:
def format_string(string):
    CD = False
    vinyl = False
    single = False

    if 'CD' in string:
        CD = True
    elif '7' in string or 'Single' in string:
        single = True
    elif '12' in string or 'Maxi' in string:
        vinyl = True
    else:
        # En caso de que ninguno de los casos anteriores se cumpla, asignamos un valor a vinyl
        vinyl = True

    # Asegurémonos de devolver siempre tres valores booleanos
    return CD, vinyl, single


df[['CD', 'vinyl', 'single']] = df['format'].apply(lambda x: pd.Series(format_string(x)))
df.drop('format', axis=1, inplace=True)

# Exportación

In [ ]:
df.to_csv('../data/ElArticoDiscos-inventory-clean.csv', index=False)